### ISSUE TITLE
Compiling and runing issues occus to me

### ISSUE THREAD

**Issue by etrigger** [avaxman/MoebiusCode#1]
Hi, thanks for sharing the cool work.
I got some compiling and runtime error as follows:

I am working on Ubuntu 14.04, with cmake 2.8.12.2, gcc 4.8.4

(1) compiling error:
-The "Filedialog.h"  may need to rename as "FileDialog.h" if it is not compiled on windows.
-In "PrescribeEdgeJumps.h", it should be #include <Eigen/Core> instead of #include <Eigen/core>
-I got a bunch of invalid use of , e.g.
MoebiusCode/external/libhedra/external/libigl/shared/cmake/../../external/nanogui/ext/eigen/Eigen/src/Core/PlainObjectBase.h:88:7: error: invalid use of incomplete type ‘struct Eigen::internal::traits<float>’

I made the following modification:
For the "mouse_move" function, Vector3f NewPos=igl::unproject<float>(Vector3f(x,y,CurrWinZ),
                                   viewer.core.view * viewer.core.model,
                                   viewer.core.proj,
                                   viewer.core.viewport);
I changed it as
 Vector3f NewPos=igl::unproject(Vector3f(x,y,CurrWinZ), (viewer.core.view * viewer.core.model).eval(), viewer.core.proj, viewer.core.viewport);

For the "mouse_down" function,
Vector3f WinCoords=igl::project<float>(V.row(i).cast<float>(),
                                        viewer.core.view * viewer.core.model,
                                        viewer.core.proj,
                                        viewer.core.viewport);
I changed it as 
Eigen::Vector3f mat(V.row(i).cast<float>().transpose());
        Vector3f WinCoords=igl::project( mat, (viewer.core.view * viewer.core.model).eval(), viewer.core.proj, viewer.core.viewport);
        
(2) Runtime error:
(1) Could you share the test sample as shown in the screenshot demo. Currently, I am trying the cube.off as follow:
OFF
8
6
24
0 0 0
0 0 1
0 1 0
0 1 1
1 0 0
1 0 1
1 1 0
1 1 1
4 0 1 3 2
4 2 3 7 6
4 4 6 7 5
4 0 4 5 1
4 1 5 7 3
4 0 2 6 4
I got some error as follow:

MoebiusCode/external/libhedra/external/libigl/shared/cmake/../../external/nanogui/ext/eigen/Eigen/src/Core/PlainObjectBase.h:241: void Eigen::PlainObjectBase<Derived>::resize(Eigen::PlainObjectBase<Derived>::Index, Eigen::PlainObjectBase<Derived>::Index) [with Derived = Eigen::Matrix<double, -1, -1>; Eigen::PlainObjectBase<Derived>::Index = long int]: Assertion `(!(RowsAtCompileTime!=Dynamic) || (nbRows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (nbCols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (nbRows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (nbCols<=MaxColsAtCompileTime)) && nbRows>=0 && nbCols>=0 && "Invalid sizes when resizing a matrix or array."' failed.
the error seems to come from "ComputeCR" inside "SetupMesh".

Could you give me some suggestion on how to solve this problem?
Thanks.

**Comment by avaxman** [comment]
Hey, thanks for taking an interest. I will try to look it over as soon as possible.

Amir.

**Comment by avaxman** [comment]
Meanwhile, I believe this is this file:

https://www.dropbox.com/s/a7iy8wy9uuk7bjw/cross_all_quads_closed.off?dl=0

Please tell me if it works for you. I haven't looked at the other issues yet (hopefully this weekend).

**Comment by etrigger** [comment]
Hi,

It works for me. Maybe my test file has some problem.
Thanks.
